### ISSUE TITLE
InnoDB conversion query does not work

### ISSUE THREAD

**Issue by markjaquith** [pantheon-systems/wp_launch_check#16]
You're suggesting that the user run this to convert their MyISAM tables to InnoDB:

```sql
UPDATE mysql.TABLES set ENGINE='InnoDB' WHERE TABLE_SCHEMA = 'pantheon';
```
Which produces this:

`ERROR 1146 (42S02): Table 'mysql.TABLES' doesn't exist`

Isn't the correct method this?

```sql
ALTER TABLE tablename ENGINE=InnoDB;
ALTER TABLE tablename2 ENGINE=InnoDB;
```

Etc?

**Comment by joshkoenig** [comment]
I think that's meant to be run locally, but it's probably mysql version dependent, which is no bueno. Thanks for flagging it.

**Comment by mikevanwinkle** [comment]
The thinking here was to make it easier convert all tables instead of having to run an ALTER statement on every table that needs migration. But I suppose there are too many dependency I hadn't consider ... i.e. permissions/versions etc. 

I think the best approach here might be not to recommend a HOW in the message but refer to an article about different ways to do it.

**Comment by bmackinney** [comment]
@calevans wrote a couple of scripts, embedded explained in this [blog post](https://pantheon.io/blog/moving-mysql-tables-myisam-innodb)
https://gist.github.com/calevans/9944410#file-mysql-to-innodb-php
and 
https://gist.github.com/calevans/9943627#file-cli-mysql-to-innodb-php

We may want to point users there.

**Comment by joshkoenig** [comment]
We should refer to this doc page:

https://pantheon.io/docs/articles/sites/database/myisam-to-innodb/
